spring:
  webflux:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    multipart:
      headers-charset: UTF-8
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      database: ${redis.database:0}
      host: ${redis.host:localhost}
      password: ${redis.password:root}
      port: ${redis.port:6379}
      timeout: 5000
      lettuce:
        pool:
          max-idle: 20
          max-wait: -1
          min-idle: 0
          max-active: 200
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          jwk-set-uri: http://auth-service/auth/oauth2/jwks
  rabbitmq:
    host: ${rbmq.host:localhost}
    port: ${rbmq.port:5672}
    username: ${rbmq.username:guest}
    password: ${rbmq.password:guest}
  cloud:
    # 在webflux需要关掉，因为spring doc不能存在mvc
    mvc:
      token-relay:
        enabled: false
    sentinel:
      log:
        dir: ./logs
    stream:
      bindings:
        operateLogProcess-out-0:
          destination: operateLogProcess
          group: logging-service
  threads:
    virtual:
      enabled: true

# 开启监控
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    jmx:
      exposure:
        include: [ 'prometheus' ]
        exclude: [ 'shutdown' ]
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  info:
    java:
      enabled: true
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
      # k8s环境会自动打开，如果此处为true则强制打开
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true
        step: 1m


logging:
  level:
    root: ${app.log-root-level:debug}
    com.anyilanxin: ${app.log-package-level:debug}
    org.camunda: ${app.log-camunda-level:debug}
    com.alibaba.nacos: error
  # 生成日志文件路径(注释不会生成)
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  file:
    name: ./logs/${spring.application.name:anyi}.log
  logback:
    rollingpolicy:
      max-history: 7
  register-shutdown-hook: true
debug: true




# api文档配置
springdoc:
  version: ${spring.application.version:1.0.0}
  api-prefix: /aycloudee/gateway # 网关swagger 调试时接口请求前缀
  other-api-docs-prefix: /aycloudee # 通过网关访问获取swagger json前缀
  gateway-api-docs-prefix: ${springdoc.api-prefix} # 网关访问获取swagger json前缀
  webflux: true #是否为webflux,用于spring doc打印信息路径判断使用
  title: ${spring.application.name:anyi}服务
  contact-email: z7630853@163.com
  contact-user: zxh
  api-docs:
    enabled: ${app.enable-doc:false}
  packages-to-scan: com.anyilanxin.cloud
  swagger-ui:
    # 网关统一地址前缀，需要特殊处理，此处还需要配置路由重写，即去掉/api/gateway(如果不需要统一前缀此处可以不用配置)
    custom-path: ${springdoc.api-prefix}/webjars/swagger-ui/index.html?configUrl=${springdoc.api-prefix}/v3/api-docs/swagger-config
    enabled: ${app.enable-doc:false}
    query-config-enabled: true
    use-root-path: true
    # 网关api docs信息
    urls:
      - name: all
        url: ${springdoc.api-prefix}/v3/api-docs
  cache:
    disabled: true


# 配置当前服务属于网关
anyi:
  resource:
    gateway: true

