-- ACT_GE_BYTEARRAY
ALTER TABLE ACT_GE_BYTEARRAY DROP CONSTRAINT ACT_FK_BYTEARR_DEPL;
-- ACT_ID_MEMBERSHIP
ALTER TABLE ACT_ID_MEMBERSHIP DROP CONSTRAINT ACT_FK_MEMB_GROUP;
ALTER TABLE ACT_ID_MEMBERSHIP DROP CONSTRAINT ACT_FK_MEMB_USER;
-- ACT_ID_TENANT_MEMBER
ALTER TABLE ACT_ID_TENANT_MEMBER DROP CONSTRAINT ACT_FK_TENANT_MEMB;
ALTER TABLE ACT_ID_TENANT_MEMBER DROP CONSTRAINT ACT_FK_TENANT_MEMB_GROUP;
ALTER TABLE ACT_ID_TENANT_MEMBER DROP CONSTRAINT ACT_FK_TENANT_MEMB_USER;

-- ACT_RE_DECISION_DEF
ALTER TABLE ACT_RE_DECISION_DEF DROP CONSTRAINT ACT_FK_DEC_REQ;

-- ACT_RU_BATCH
ALTER TABLE ACT_RU_BATCH DROP CONSTRAINT ACT_FK_BATCH_JOB_DEF;
ALTER TABLE ACT_RU_BATCH DROP CONSTRAINT ACT_FK_BATCH_MONITOR_JOB_DEF;
ALTER TABLE ACT_RU_BATCH DROP CONSTRAINT ACT_FK_BATCH_SEED_JOB_DEF;

-- ACT_RU_CASE_EXECUTION
ALTER TABLE ACT_RU_CASE_EXECUTION DROP CONSTRAINT ACT_FK_CASE_EXE_CASE_DEF;
ALTER TABLE ACT_RU_CASE_EXECUTION DROP CONSTRAINT ACT_FK_CASE_EXE_CASE_INST;
ALTER TABLE ACT_RU_CASE_EXECUTION DROP CONSTRAINT ACT_FK_CASE_EXE_PARENT;

-- ACT_RU_CASE_SENTRY_PART
ALTER TABLE ACT_RU_CASE_SENTRY_PART DROP CONSTRAINT ACT_FK_CASE_SENTRY_CASE_EXEC;
ALTER TABLE ACT_RU_CASE_SENTRY_PART DROP CONSTRAINT ACT_FK_CASE_SENTRY_CASE_INST;

-- ACT_RU_EVENT_SUBSCR
ALTER TABLE ACT_RU_EVENT_SUBSCR DROP CONSTRAINT ACT_FK_EVENT_EXEC;

-- ACT_RU_EXECUTION
ALTER TABLE ACT_RU_EXECUTION DROP CONSTRAINT ACT_FK_EXE_PARENT;
ALTER TABLE ACT_RU_EXECUTION DROP CONSTRAINT ACT_FK_EXE_PROCDEF;
ALTER TABLE ACT_RU_EXECUTION DROP CONSTRAINT ACT_FK_EXE_PROCINST;
ALTER TABLE ACT_RU_EXECUTION DROP CONSTRAINT ACT_FK_EXE_SUPER;

-- ACT_RU_EXT_TASK
ALTER TABLE ACT_RU_EXT_TASK DROP CONSTRAINT ACT_FK_EXT_TASK_ERROR_DETAILS;
ALTER TABLE ACT_RU_EXT_TASK DROP CONSTRAINT ACT_FK_EXT_TASK_EXE;

-- ACT_RU_IDENTITYLINK
ALTER TABLE ACT_RU_IDENTITYLINK DROP CONSTRAINT ACT_FK_ATHRZ_PROCEDEF;
ALTER TABLE ACT_RU_IDENTITYLINK DROP CONSTRAINT ACT_FK_TSKASS_TASK;

-- ACT_RU_INCIDENT
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_CAUSE;
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_EXE;
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_JOB_DEF;
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_PROCDEF;
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_PROCINST;
ALTER TABLE ACT_RU_INCIDENT DROP CONSTRAINT ACT_FK_INC_RCAUSE;

-- ACT_RU_JOB
ALTER TABLE ACT_RU_JOB DROP CONSTRAINT ACT_FK_JOB_EXCEPTION;

-- ACT_RU_TASK
ALTER TABLE ACT_RU_TASK DROP CONSTRAINT ACT_FK_TASK_CASE_DEF;
ALTER TABLE ACT_RU_TASK DROP CONSTRAINT ACT_FK_TASK_CASE_EXE;
ALTER TABLE ACT_RU_TASK DROP CONSTRAINT ACT_FK_TASK_EXE;
ALTER TABLE ACT_RU_TASK DROP CONSTRAINT ACT_FK_TASK_PROCDEF;
ALTER TABLE ACT_RU_TASK DROP CONSTRAINT ACT_FK_TASK_PROCINST;

-- ACT_RU_VARIABLE
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_BATCH;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_BYTEARRAY;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_CASE_EXE;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_CASE_INST;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_EXE;
ALTER TABLE ACT_RU_VARIABLE DROP CONSTRAINT ACT_FK_VAR_PROCINST;




