kind: Deployment
apiVersion: apps/v1
metadata:
  name: anyi-cloud-service-storage
  namespace: anyicloud
  labels:
    app: anyi-cloud-service-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anyi-cloud-service-storage
  template:
    metadata:
      labels:
        app: anyi-cloud-service-storage
      annotations:
        kubesphere.io/creator: admin
        kubesphere.io/imagepullsecrets: '{"anyi-container-storage":"harbor"}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-jxpkim
          persistentVolumeClaim:
            claimName: aycloudee-pvc
      containers:
        - name: anyi-container-storage
          image: >-
            harbor.anyilanxin.com/anyi/anyi-cloud-service-storage:@version@-@k8sRevision@
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: anyicloud-common-env
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-jxpkim
              mountPath: /app/upload
              subPath: storage
          #          livenessProbe:
          #            httpGet:
          #              path: /storage/actuator/health/liveness
          #              port: 80
          #              scheme: HTTP
          #            timeoutSeconds: 3
          #            periodSeconds: 10
          #            successThreshold: 1
          #            failureThreshold: 3
          #          readinessProbe:
          #            httpGet:
          #              path: /storage/actuator/health/readiness
          #              port: 80
          #              scheme: HTTP
          #            timeoutSeconds: 3
          #            periodSeconds: 10
          #            successThreshold: 1
          #            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: { }
      imagePullSecrets:
        - name: harbor
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
