###############################################################################
#                          Generated on middleware                            #
###############################################################################
version: '3'
services:
  # rabbitmq
  rabbitmq-server:
    image: rabbitmq:3.10.1-management
    container_name: rabbitmq-server
    restart: always
    networks:
      - middleware_net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"


networks:
  middleware_net:
    driver: bridge
