###############################################################################
#                          Generated on skillfullcloud                              #
###############################################################################
version: '3'
services:
  gateway-service:
    image: skillfull-gateway-service:0.9.9
    container_name: gateway-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    ports:
      - "20076:80"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net


  auth-service:
    image: skillfull-auth-service:0.9.9
    container_name: auth-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net


  logging-service:
    image: skillfull-logging-service:0.9.9
    container_name: logging-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net


  message-service:
    image: skillfull-message-service:0.9.9
    container_name: message-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net



  monitor-service:
    image: skillfull-monitor-service:0.9.9
    container_name: monitor-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net


  process-service:
    image: skillfull-process-service:0.9.9
    container_name: process-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net



  storage-service:
    image: skillfull-storage-service:0.9.9
    container_name: storage-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - /opt/containerd/.data/upload:/app/upload
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net


  system-service:
    image: skillfull-system-service:0.9.9
    container_name: system-service
    restart: always
    environment:
      PROFILES_ACTIVE: test
      CONFIG_ENABLE: 'true'
      NACOS_PASSWORD: skillfullcloud
      NACOS_USERNAME: skillfullcloud
      NACOS_ADDR: nacos-server:8848
      NACOS_NAMESPACE: skillfullcloud
      server.port: 80
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - database_database_net
      - middleware_middleware_net
      - nacos_nacos_net
      - seata_seata_net



networks:
  database_database_net:
    external: true
  middleware_middleware_net:
    external: true
  nacos_nacos_net:
    external: true
  seata_seata_net:
    external: true

