# 数据源配置
spring:
  datasource:
    dynamic:
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/anyicloud_message_service?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatement=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
      # 开启seata代理
      seata: false


redis:
  host: localhost
  port: 6379
  password: root
  database: 15


rbmq:
  host: localhost
  port: 5672
  relay-port: 61613 #stomp端口
  username: guest
  password: guest


app:
  log-root-level: info
  log-package-level: debug
  enable-gray: true # 是否启用灰度
  enable-doc: true # 是否打开swagger



# 资源白名单设置
anyi:
  resource:
    dev-white-list:
      - /swagger-ui.html;get
      - /swagger-ui/**;get
      - /v3/api-docs/**;get
springdoc:
  auth2-prefix: http://127.0.0.1:604/authorization
